<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Header</title>
    <link rel="stylesheet" href="assets/styles/css/style.css" type="text/css" />
</head>
<body>
    <header>
        <nav id="nav-header">
            <ul>
                <li><a href="index.php?route=homepage">Accueil</a></li>
                <li><a href="index.php?route=connexion">Connexion</a></li>
                <li><a href="index.php?route=creer-un-compte">Création de compte</a></li>
            </ul>
        </nav>
    </header>
</body>
</html>