<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Header</title>
    <link rel="stylesheet" href="../assets/styles/css/style.css" type="text/css" />
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="../pages/homepage.php">Accueil</a></li>
                <li><a href="../pages/login.php">Connexion</a></li>
                <li><a href="../pages/register.php">Création de compte</a></li>
            </ul>
        </nav>
    </header>
</body>
</html>