<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Login-Form</title>
</head>
<body>
    <form method="POST" action="index.php">
        <label for="login">Login</label>
        <input type="text" name="login" id="login"/>
        <label for="password">Password</label>
        <input type="text" name="password" id="password"/>
        <input type="hidden" name="formName" id="formName"/>
        <input type="submit" value="Submit"/>
    </form>
</body>
</html>