<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Login-Form</title>
    <link rel="stylesheet" href="assets/styles/css/style.css" type="text/css" />
</head>
<body>
    
    <form method="POST" action="index.php">
        <label for="login">Login</label>
        <input type="text" name="login" id="login"/>
        <label for="log-password">Password</label>
        <input type="password" name="log-password" id="log-password" autocomplete="new-password"/>
        <input type="hidden" name="formName" id="formName"/>
        <input type="submit" value="Submit"/>
    </form>
    
</body>
</html>