<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Register-Form</title>
</head>
<body>
    <form method="POST" action="index.php">
        <label for="firstname">FirstName</label>
        <input type="text" name="firstname" id="firstname"/>
        <label for="lastname">LastName</label>
        <input type="text" name="lastname" id="lastname"/>
        <label for="email">Email</label>
        <input type="email" name="email" id="email"/>
        <label for="password">Password</label>
        <input type="password" name="password" id="password"/>
        <label for="confirm_password">Confirm Password</label>
        <input type="password" name="confirm_password" id="confirm_password"/>
        <input type="hidden" name="formName"/>
        <input type="submit" value="Submit"/>
    </form>
</body>
</html>